on:
  push:
    branches: [main]

permissions:
  contents: read
  issues: read
  pull-requests: read

jobs:
  linear-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Linear Release
        uses: zeet-co/linear-release/packages/linear-release-action@main
        env:
          LINEAR_API_KEY: ${{ secrets.LINEAR_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # with:
        #   team: 'ZEET'
        #   from: 'In Staging'
        #   to: 'In Production'
