on:
  push:
    branches: [main]

jobs:
  linear-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Linear Release
        uses: zeet-co/linear-release/packages/linear-release-action@main
        # with:
        #   team: 'ZEET'
        #   from: 'In Staging'
        #   to: 'In Production'
