on:
  push:
    branches: [main]

jobs:
  linear-release:
    runs-on: ubuntu-latest
    steps:
      - name: Linear Release
        uses: zeet-co/linear-release/packages/linear-release-action
        # with:
        #   team: 'ZEET'
        #   from: 'In Staging'
        #   to: 'In Production'
